/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
export enum AppState {
  IDLE,
  LOADING,
  SUCCESS,
  ERROR,
}

export enum ShotStatus {
  PENDING_JSON = 'PENDING_JSON', // Waiting for VEO JSON to be generated
  GENERATING_JSON = 'GENERATING_JSON', // VEO JSON generation in progress
  PENDING_KEYFRAME_PROMPT = 'PENDING_KEYFRAME_PROMPT', // JSON created, waiting for keyframe prompt text generation
  GENERATING_KEYFRAME_PROMPT = 'GENERATING_KEYFRAME_PROMPT', // Keyframe prompt text generation in progress
  NEEDS_KEYFRAME_GENERATION = 'NEEDS_KEYFRAME_GENERATION', // Keyframe prompt text available, image not yet generated
  GENERATING_IMAGE = 'GENERATING_IMAGE', // Image generation in progress
  NEEDS_REVIEW = 'NEEDS_REVIEW', // Image generated, awaiting user approval
  GENERATION_FAILED = 'GENERATION_FAILED', // Keyframe or JSON generation failed
}

export enum VeoStatus {
  IDLE = 'IDLE',
  QUEUED = 'QUEUED', // Task submitted
  GENERATING = 'GENERATING', // 0 in API
  COMPLETED = 'COMPLETED', // 1 in API
  FAILED = 'FAILED', // 2 or 3 in API
}

export enum LogType {
  INFO = 'INFO',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  STEP = 'STEP',
}

export interface LogEntry {
  timestamp: string;
  message: string;
  type: LogType;
}

// From MEMO 1 for ScenePlan + Extend Logic
export interface ScenePlanBeat {
  beat_id: string;
  label: string;
  priority: number;
  min_s: number;
  max_s: number;
}

export interface ExtendPolicy {
  allow_extend: boolean;
  extend_granularity_s: number;
  criteria: string[];
}

export interface ScenePlan {
  scene_id: string;
  scene_title: string;
  goal_runtime_s: number;
  beats: ScenePlanBeat[];
  extend_policy: ExtendPolicy;
}

// Based on VEO 3.1 JSON Schema from user's knowledge doc
export interface VeoShot {
  shot_id: string;
  scene: {
    context: string;
    visual_style: string;
    lighting: string;
    mood: string;
    aspect_ratio: '16:9' | '9:16';
    duration_s: 4 | 6 | 8;
  };
  character: {
    name: string;
    gender_age: string;
    description_lock: string;
    behavior: string;
    expression: string;
  };
  camera: {
    shot_call: string;
    movement: string;
    negatives?: string;
  };
  audio: {
    dialogue: string;
    delivery: string;
    ambience?: string;
    sfx?: string;
  };
  flags: {
    continuity_lock: boolean;
    do_not: string[];
    anti_artifacts: string[];
    conflicts: string[];
    warnings: string[];
    cv_updates: string[];
  };
}

export interface VeoShotWrapper {
  unit_type: 'shot' | 'extend';
  chain_id?: string;
  segment_number?: number;
  segment_count?: number;
  target_duration_s?: number;
  stitching_notes?: string;
  clip_strategy?: string;
  directorNotes?: string; // Added for natural language guidance on extend blocks
  veo_shot: VeoShot;
}

// For uploaded reference images
export interface IngredientImage {
  base64: string;
  mimeType: string;
}

export type AssetType = 'character' | 'location' | 'prop' | 'style';

export interface ProjectAsset {
  id: string;
  name: string;
  description: string; // AI inferred description
  type: AssetType;
  image: IngredientImage | null; // The uploaded image
}

// The interactive shot object used in the app's state
export interface Shot {
  id: string; // A unique ID for React keys, from shot_id
  status: ShotStatus;
  pitch: string; // The natural language pitch
  sceneName?: string; // Descriptive name for the scene this shot belongs to
  veoJson?: VeoShotWrapper; // Now uses the wrapper type
  keyframePromptText?: string; // The text prompt generated for the keyframe image
  keyframeImage?: string; // base64 string
  errorMessage?: string; // If image generation fails
  
  // New: The IDs of the assets specifically used for this shot.
  selectedAssetIds: string[]; 
  
  // Deprecated but kept for compatibility
  ingredientImages?: IngredientImage[];

  // VEO VIDEO GENERATION FIELDS
  veoTaskId?: string;
  veoStatus?: VeoStatus;
  veoVideoUrl?: string;
  veoError?: string;
}

export type ShotBook = Shot[];

// For API call token usage and cost estimation
export interface ApiCallSummary {
  pro: number; // Number of Gemini 2.5 Pro calls
  flash: number; // Number of Gemini 2.5 Flash calls (text generation)
  image: number; // Number of image generation calls
  proTokens: { input: number; output: number; };
  flashTokens: { input: number; output: number; };
}

// Estimated API pricing (as of a hypothetical latest update - always verify with GCP pricing)
export const GEMINI_PRO_INPUT_COST_PER_MILLION_TOKENS = 7.00; // USD
export const GEMINI_PRO_OUTPUT_COST_PER_MILLION_TOKENS = 21.00; // USD
export const GEMINI_FLASH_INPUT_COST_PER_MILLION_TOKENS = 0.35; // USD
export const GEMINI_FLASH_OUTPUT_COST_PER_MILLION_TOKENS = 1.05; // USD
export const IMAGEN_COST_PER_IMAGE = 0.005; // USD per image generated by gemini-2.5-flash-image